import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { useNavigate } from 'react-router-dom'
import AppLayout from '../components/layout/AppLayout'
import { apiError } from '../api/client'
import { listTestSets, listFlows, type TestSet, type FlowSummary } from '../api/testset'
import { listGlobalRuns, type GlobalRun } from '../api/runs'
import { RunResultDetail } from '../components/results/ResultsPanel'

export default function Runs() {
  const nav = useNavigate(); const [sets, setSets] = useState<TestSet[]>([]); const [flows, setFlows] = useState<FlowSummary[]>([]); const [runs, setRuns] = useState<GlobalRun[]>([]); const [total, setTotal] = useState(0); const [setID, setSetID] = useState(0); const [flowID, setFlowID] = useState(0); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [error, setError] = useState(''); const [selected, setSelected] = useState<GlobalRun>()
  const loadFlows = async (id: number) => { if (!id) { setFlows([]); return }; try { setFlows(await listFlows(id)) } catch (e) { setError(apiError(e)) } }
  const load = async () => { setError(''); try { const data = await listGlobalRuns({ test_set_id: setID || undefined, flow_id: flowID || undefined, status: status || undefined, from: from || undefined, to: to || undefined }); setRuns(data.runs); setTotal(data.total) } catch (e) { setError(apiError(e)) } }
  useEffect(() => { listTestSets().then(setSets).catch((e) => setError(apiError(e))); load() }, [])
  return <AppLayout title="执行记录"><div className="runs-page"><div className="page-head"><div><h1>全局执行记录</h1><p className="muted">查询可访问测试集和 Flow 的历史执行。</p></div></div>
    <div className="card filters"><select value={setID} onChange={(e) => { const id = Number(e.target.value); setSetID(id); setFlowID(0); loadFlows(id) }}><option value={0}>全部测试集</option>{sets.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={flowID} onChange={(e) => setFlowID(Number(e.target.value))}><option value={0}>全部 Flow</option>{flows.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">全部结果</option><option value="success">成功</option><option value="failed">失败</option></select><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /><button className="primary" onClick={load}>查询</button><button onClick={() => { setSetID(0); setFlowID(0); setStatus(''); setFrom(''); setTo(''); setFlows([]); setTimeout(load, 0) }}>重置</button></div>
    {error && <p className="err">{error}</p>}<p className="muted">共 {total} 条记录</p><div className="card table-wrap"><table className="table runs-table"><thead><tr><th>测试集</th><th>Flow</th><th>版本</th><th>结果</th><th>开始时间</th><th>操作</th></tr></thead><tbody>{runs.map((r) => <tr key={r.id}><td>{r.test_set_name}</td><td>{r.flow_name}</td><td>{r.version_id ? `v${r.version_no}` : '草稿试运行'}</td><td className={r.status === 'failed' ? 'err' : 'ok'}>{r.status === 'failed' ? '失败' : '成功'}</td><td>{new Date(r.started_at).toLocaleString('zh-CN')}</td><td><button className="link" onClick={() => setSelected(r)}>查看结果</button><button className="link" onClick={() => nav(`/flows/${r.flow_id}`)}>进入 Flow</button></td></tr>)}</tbody></table>{runs.length === 0 && <p className="muted">暂无符合条件的执行记录。</p>}</div>{selected && createPortal(<div className="run-popover" style={{ right: 24, top: 88 }}><div className="run-popover-head"><span className="strong">{selected.test_set_name} · {selected.flow_name}</span><button className="link" onClick={() => setSelected(undefined)}>✕</button></div><RunResultDetail run={selected} /></div>, document.body)}</div></AppLayout>
}
